language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
install:
   - pip install -r requirements.txt
   - pip install coveralls
# command to run tests
script:
 coverage run --source=aws_iot_sdk setup.py test
after_success:
 coveralls